spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/graphql_compras?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
#        ddl-auto: none
        format_sql: true

  flyway:
    locations: classpath:db/migration

#logging:
#  pattern:
#    console: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
#    level:
#      org:
#        hibernate:
#          SQL: debug

server:
  port: 8087